#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    #line 2 "..\..\Views\Shared\_Layout.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Layout.cshtml"
    using AudioAgent.Services.Texts;
    
    #line default
    #line hidden
    using AudioAgent.WebApp;
    using AudioAgent.WebApp.Extensions;
    
    #line 4 "..\..\Views\Shared\_Layout.cshtml"
    using AudioAgent.WebApp.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class _Views_Shared__Layout_cshtml : System.Web.WebPages.HelperPage
    {
    }
}
#pragma warning restore 1591
